### DISCUSSION TITLE
Highlight Parts of Speech Styling Showcase

### DISCUSSION THREAD

**Discussion by SkepticMystic** [SkepticMystic/nlp#4] [Show and tell]
By default, the `Highlight Parts of Speech` command doesn't apply any styles, it only adds the css classes for _you_ to style.
There are two reasons for this, 
1. I'm not good at styling 😅, and 
2. it enables you to stye the parts of speech however you want!

And so, it would be great to see how you have set up your PoS styling. Please feel free to share some screenshots of your setup, and the actual css if you're open to that 😄

**Comment by chrisgrieser** [comment]
iA Writer like Language Syntax Highlighting, with options for the Style Settings Plugin.

```css
/* NLP Syntax Highlighting */

/* CSS Laboratory */

.theme-light {
	--verb: hsl(220 100% 40%);
	--adjective: hsl(38 100% 35%);
	--adverb: hsl(303 100% 32%);
	--conjunction: hsl(120 100% 25%);
	--noun: hsl(0 80% 40%);
}

.theme-dark {
	--verb: hsl(220 100% 60%);
	--adjective: hsl(38 100% 50%);
	--adverb: hsl(303 80% 45%);
	--conjunction: hsl(120 100% 35%);
	--noun: hsl(0 70% 55%);
}

body:not(.no-verbs) .Verb { color: var(--verb) }
body:not(.no-adjectives) .Adjective { color: var(--adjective) }
body:not(.no-adverbs) .Adverb { color: var(--adverb) }
body:not(.no-conjunctions) .Conjunction { color: var(--conjunction) }
body:not(.no-nouns) .Noun { color: var(--noun) }

/* @settings
name: 'NLP Plugin: Syntax Highlighting'
id: nlp-linguistic-syntax-highlighting
settings:
  -
	 id: no-nouns
	 title: Do not highlight nouns.
	 type: class-toggle
	 default: false
  -
	 id: no-verbs
	 title: Do not highlight verbs.
	 type: class-toggle
	 default: false
  -
	 id: no-adjectives
	 title: Do not highlight adjectives.
	 type: class-toggle
	 default: false
  -
	 id: no-adverbs
	 title: Do not highlight adverbs.
	 type: class-toggle
	 default: false
  -
	 id: no-conjunctions
	 title: Do not highlight conjunctions.
	 type: class-toggle
	 default: false
  -
*/
```

<img width="870" alt="Screenshot 2021-12-22 15 06 45" src="https://user-images.githubusercontent.com/73286100/147105183-910dec27-d428-4413-81f0-631c7e5bbebf.png">
<img width="872" alt="Screenshot 2021-12-22 15 07 02" src="https://user-images.githubusercontent.com/73286100/147105216-b1e59043-9583-4471-870a-a7f4150807c1.png">
<img width="1085" alt="Screenshot 2021-12-22 15 16 46" src="https://user-images.githubusercontent.com/73286100/147107152-97ed6365-094a-4c12-b6a5-7e640145ed09.png">
